### ISSUE TITLE
Rails db migrate fail

### ISSUE THREAD

**Issue by seapy** [aws/aws-xray-sdk-ruby#1]
Deploy failed when execute `db:migrate`

this is rails project and initializer is here

```ruby
Rails.application.config.xray = {
  # default segment name generated by XRay middleware
  name: 'cvsinfo_web',
  patch: %I[net_http aws_sdk],
  # record db transactions as subsegments
  active_record: true
}
```

Works if commented `active_record: true` 

here is error log

```
01:07 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 XRay::ContextMissingError: Can not find any active segment or subsegment.
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/context/default_context.rb:58:in `handle_context_missing'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/context/default_context.rb:35:in `current_entity'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/recorder.rb:122:in `current_entity'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/recorder.rb:62:in `begin_subsegment'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/facets/rails/active_record.rb:22:in `record'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/facets/rails/active_record.rb:65:in `block in <top (required)>'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:127:in `finish'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `block in finish'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `each'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `finish'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:27:in `instrument'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:59:in `query'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `query_value'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:329:in `get_advisory_lock'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1314:in `with_advisory_lock'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
      01 /home/ubuntu/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
      01 /home/ubuntu/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
      01 Tasks: TOP => db:migrate
      01 (See full trace by running task with --trace)
```

**Comment by haotianw465** [comment]
Hi, you can change `context_missing` to `LOG_ERROR` to avoid this issue. You can find more information about this option here: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-ruby-configuration.html

The challenge is that we use active support event listener to record SQL queries. https://github.com/aws/aws-xray-sdk-ruby/blob/master/lib/aws-xray-sdk/facets/rails/active_record.rb#L62

But when doing SQL recording the X-Ray event handler doesn't know if this SQL event is from an incoming request or a `db migrate` command. 

A workaround for the SDK is to make SQL event handler drop the database subsegment on `db migrate`, but the downside is that the handler will not be able to respect the `context_missing` setting and it will always act as if this option is set to `LOG_ERROR`.

We are open to here any suggestions.

**Comment by seapy** [comment]
change `context_missing` to `LOG_ERROR` but another error is happen.

```
01:25 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 NoMethodError: undefined method `start_time=' for nil:NilClass
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/facets/rails/active_record.rb:23:in `record'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/aws-xray-sdk-0.9.0/lib/aws-xray-sdk/facets/rails/active_record.rb:65:in `block in <top (requi…
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:127:in `finish'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `block in finish'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `each'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `finish'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:27:in `instrument'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:59…
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:70:i…
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:329:in `get_ad…
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1314:in `with_advisory_lock'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top …
      01 /home/ubuntu/www/cvsinfo/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
      01 /home/ubuntu/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
      01 /home/ubuntu/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
      01 Tasks: TOP => db:migrate
      01 (See full trace by running task with --trace)
      01 E, [2018-01-21T19:48:30.866629 #25465] ERROR -- : can not find the current context.
```

**Comment by haotianw465** [comment]
Hi, the issue in `context_missing` set to `LOG_ERROR` is addressed in the new released version 0.10.0. Please let me know if you have any questions.

We are considering to make `active_record` capture to always act as `LOG_ERROR` in case of missing context but we would need to collect more feedback to make that move.

**Comment by LarsFronius** [comment]
I got around the issue by patching my Rakefile up to create segments before the tasks are run:
```ruby
Rake::Task.tasks.each do |t|
  t.enhance do
    XRay.recorder.begin_segment "mothership_#{t.name}"
  end
end
```

It would be great if the SDK provided more guidance on how to deal with tests and one-off jobs though.

**Comment by haotianw465** [comment]
Thank you for your feedback @LarsFronius. We will update our user guide to reflect this.
