### ISSUE TITLE
invalid configuration option `:xray_recorder' on Kinesis

### ISSUE THREAD

**Issue by mt-kelvintaywl** [aws/aws-xray-sdk-ruby#51]
Hi guys, are there better documentations on what dependencies i'll need to update for working with instrumenting this SDK with Ruby Lambda functions?

I [followed the example](https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/blank-ruby/function/lambda_function.rb#L5-L22), and have tried to instrument X-Ray with a Lambda function (with Kinesis data stream as its event source).

```rb
require 'aws-sdk-lambda'
require 'aws-xray-sdk/lambda'

require './lib/logger.rb'

xray_config = {
  context_missing: 'LOG_ERROR',
  logger: LOGGER
}
XRay.recorder.configure(xray_config)

def my_function(event:, context:)
  client = Aws::Lambda::Client.new

  # business logic

  client.get_account_settings.account_usage.to_h
end
```

However, I seem to hit a possible bug(?) :
```
invalid configuration option `:xray_recorder'
```

The redacted error trace:

```

"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/configuration.rb:162:in `block in apply_options'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/configuration.rb:161:in `each'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/configuration.rb:161:in `apply_options'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/configuration.rb:149:in `build!'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/base.rb:62:in `build_config'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/base.rb:19:in `initialize'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-kinesis-1.20.0/lib/aws-sdk-kinesis/client.rb:273:in `initialize'",
"/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/base.rb:99:in `new'",
```

My dependencies are below:

```
GEM
  remote: https://rubygems.org/
  specs:
    ...
    aws-eventstream (1.1.0)
    aws-partitions (1.343.0)
    aws-record (2.4.0)
      aws-sdk-dynamodb (~> 1.18)
    aws-sdk-core (3.104.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-dynamodb (1.37.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kinesis (1.26.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-lambda (1.31.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-sns (1.20.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-xray (1.4.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.2.1)
      aws-eventstream (~> 1, >= 1.0.2)
    aws-xray-sdk (0.11.5)
      aws-sdk-xray (~> 1.4.0)
      multi_json (~> 1)
...

DEPENDENCIES
  aws-record
  aws-sdk-kinesis
  aws-sdk-lambda
  aws-sdk-sns
  aws-xray-sdk
  ...
```

Not sure if it's related to https://github.com/aws/aws-xray-sdk-ruby/issues/26 but the fix mentioned here shows the Kinesis service is whitelisted so I'm not sure what exactly is going wrong?
Would i just need to bump my dependencies on the `aws-sdk-*` gems?

Thank you! 🙏

**Comment by srprash** [comment]
Hi @mt-kelvintaywl, apologies for the delay in response. I believe having kinesis as your event source for the lambda function wouldn't cause the error since the X-Ray instrumentation is within the function and the message from kinesis stream is passed in as an event. Are you creating a kinesis client and/or calling kinesis service from within your lambda function?

**Comment by mt-kelvintaywl** [comment]
Hi @srprash, thank you for reaching out and my apologies for the late response here myself too :bow:

> I believe having kinesis as your event source for the lambda function wouldn't cause the error since the X-Ray instrumentation is within the function and the message from kinesis stream is passed in as an event.

Indeed, i would believe so too. Yet, this was happening.
For context:

- this Lambda is setup to be triggered by the Kinesis stream events, and this lambda also sends a payload to another Kinesis stream (hence the `aws-sdk-kinesis` gem as a dependency). 
- We are deploying the Lambda code via [Serverless Framework](https://serverless.com) and also updated the Lambda's IAM role to allow for X-ray actions. 


in the end, i've reverted and abandoned the instrumentation.
Let me close this for now, and perhaps re-open it once I can re-produce once once 🙇

**Comment by srprash** [comment]
Hi @mt-kelvintaywl 
Thanks for providing more details here. I will try to reproduce this on my end as well. Please feel to re-open if you come across it in the future.

**Comment by omenking** [comment]
I'm getting this error as well, just trying to do general instrutumentation.
Following what we have here:

https://docs.amazonaws.cn/en_us/lambda/latest/dg/ruby-tracing.html

In JS we have:
```
var AWSXRay = require('aws-xray-sdk');
var AWS = AWSXRay.captureAWS(require('aws-sdk'));
```

So its my assumption once things are instrumented I'll be able to see functions passed downstream, Since right now I'm just trying to see my Lambda call SNS in my service map. but how Ruby configures vs NodeJS is confusing me since next to no examples.

**Comment by omenking** [comment]
I looked into the the gems and noticed something called patching, so I added the following to my configuration and this stopped the error. Still can't see my Lambda calling SNS in my Service Map.
```
require 'aws-xray-sdk'

config = {
  patch: %I[net_http aws_sdk]
}

XRay.recorder.configure(config)
```

**Comment by omenking** [comment]
What is odd is that it looks like  require 'aws-xray-sdk/lambda' should already patch, which is what I'm including...
```
# Set `XRAY_LAMBDA_PATCH_CONFIG` before requiring `aws-xray-sdk/lambda`
# to configure which libraries (if any) to instrument.
#
# By default, both `net_http` and `aws_sdk` will be instrumented
unless defined? XRAY_LAMBDA_PATCH_CONFIG
  XRAY_LAMBDA_PATCH_CONFIG = %I[net_http aws_sdk]
end

# Configure the XRay.recorder with Lambda specific config.
#
# From here, a lambda may create subsegments manually, or via
# the instrumented libraries setup by XRAY_LAMBDA_PATCH_CONFIG
XRay.recorder.configure(
  patch: XRAY_LAMBDA_PATCH_CONFIG,
  context: XRay::LambdaContext.new,
  streamer: XRay::LambdaStreamer.new
)
```

**Comment by jessedoyle** [comment]
I've encountered similar errors a number of times now with this library. It's probably worth it to take some time and document the issue.

When this invalid configuration option error occurs it's generally for one of two reasons:

1. The client/service you're trying to use isn't [whitelisted in this library yet](https://github.com/aws/aws-xray-sdk-ruby/blob/b08a00bd167d392893525997a65ee26868305717/lib/aws-xray-sdk/facets/resources/aws_services_allowlist.rb#L5-L232).
2. The application code is attempting to patch the AWS SDK _before_ the SDK clients have been loaded. This isn't documented anywhere to my knowledge, but ensure your SDK clients are required prior to loading the Xray patches:

i.e.

```ruby
require 'aws-sdk-lambda'
require 'aws-sdk-kinesis'
# be sure to require any other AWS SDK clients your app will use here
require 'aws-xray-sdk/lambda'
```
